version: 2.1

jobs:
    build:
        docker:
            - image: node:14

        steps:
            - checkout
            - run:
                  name: Change to frontend directory and Install dependencies
                  command: |
                      cd frontend
                      npm install
            -run:
                 name: Run tests
                 command: |
                    cd frontend
                    npm test
