version: 2.1

jobs:
    build:
        docker:
            - image: node:14

        steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: |
                      cd frontend
                      npm install
            - run:
                  name: Run Tests
                  command: |
                      cd frontend
                      npm test
