version: 2.1

jobs:
    build:
        docker:
            - image: node:14
        working_directory: /app
        steps:
            - checkout
            - run: npm install
            - run: npm test

workflows:
    version: 2
    build:
        jobs:
            - build
