version: 2.1

jobs:
    build:
        docker:
            - image: node:14

        steps:
            - checkout
            - run:
                  name: ls
                  command: ls
            - run:
                  name: Change to frontend directory
                  command: cd frontend
            - run:
                  name: Install dependencies
                  command: npm install
            - run:
                  name: Print Hello
                  command: ls
