version: 2.1

jobs:
    build:
        docker:
            - image: node:14
        working_directory: /frontend

        steps:
            - checkout
            - run: npm install
            - run: npm test
